services:
  postgres:
    image: postgres:16.3
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres

  purple_chili_app:
    image: python:3.12
    build:
      context: .
      dockerfile: docker/purple_chili_app/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - postgres
