name: ${DOCKER_IMAGE?DOCKER_IMAGE variable not set}
services:
  postgres:
    image: postgres:16.3
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT?POSTGRES_PORT variable not set}
      - POSTGRES_DB=${POSTGRES_DB?POSTGRES_DB variable not set}
      - POSTGRES_USER=${POSTGRES_USER?POSTGRES_USER variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?POSTGRES_PASSWORD variable not set}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres

  purple_chili_app:
    image: python:3.12
    ports:
      - 5678:5678
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - postgres
    command: >
      bash -c "cd /app
      && pip install --no-cache-dir uv
      && uv pip install --system --no-cache -r requirements-dev.txt
      && python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m uvicorn app.main:app --host 0.0.0.0 --port 8000"
